### ISSUE TITLE
Metadata fields

### ISSUE THREAD

**Issue by adedw** [Baklanov-Soft/image-hosting-storage#4]
should we keep original file name?
or replace it with uuid?
what fields should be included in the metadata?

**Comment by DenisNovac** [comment]
I'd say original name as a string for user convenience (with ability to rename), uuid as PK.
Time of upload would be nice, "hidden" boolean tag for moderation (i guess it should be an index since literally every query would have this in WHERE clause).

Something like this 
```sql
CREATE TABLE images (
   uuid UUID PRIMARY KEY,
   user_id UUID FOREIGN KEY (users(uuid)),
   name VARCHAR(255),
   hidden BOOLEAN INDEX,
   uploaded_at DATETIME
)
```

For user_id let's make anonymous user at the beginning of the app and just load every image as anonymous for now.

**Comment by adedw** [comment]
whats about move forbiddenness to category entity?
should we have a category entity?
or where/how to store the image category?

![image](https://github.com/Baklanov-Soft/image-hosting-storage/assets/6439709/cbb95ccc-5e04-47fe-ade4-fb0b3c932aba)

**Comment by DenisNovac** [comment]
>or where/how to store the image category?

I believe we need to only store forbidden categories and use unique index on them. No keys relations, just cross-check with `WHERE NOT IN (SELECT * FROM forbidden_categories)` when requesting the images.
